//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int LikeID { get; set; }
        public int ChatID { get; set; }
        public string UserName { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
